sonar.projectKey=cookiebites-sqa
sonar.projectName=CookieBites SQA
sonar.projectVersion=0.0.1-SNAPSHOT
sonar.sourceEncoding=UTF-8

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.exclusions=target/**,src/main/java/com/example/cookiebites/Front/View/**/*.html,src/main/java/com/example/cookiebites/Front/View/img/**
sonar.test.inclusions=src/test/java/**/*.java